export function fitImage(width,height,imageWidth,imageHeight,contain=false){const scale=(contain?Math.min:Math.max)(width/imageWidth,height/imageHeight);return{width:imageWidth*scale,height:imageHeight*scale,left:(width-imageWidth*scale)/2,top:(height-imageHeight*scale)/2};}
export function targetBounds(polygon){const xs=polygon.map(p=>p[0]),ys=polygon.map(p=>p[1]);return{left:Math.min(...xs),top:Math.min(...ys),width:Math.max(...xs)-Math.min(...xs),height:Math.max(...ys)-Math.min(...ys)};}
export function touchBounds(box,minimum=44){const width=Math.max(minimum,box.width),height=Math.max(minimum,box.height);return{left:box.left-(width-box.width)/2,top:box.top-(height-box.height)/2,width,height};}
export function mountFoundation({getState}){
 const manifest=JSON.parse(document.querySelector('#foundation-manifest').textContent),mobile=matchMedia('(max-aspect-ratio:4/5)'),scenes=[...document.querySelectorAll('[data-foundation-scene]')];
 const labels={en:{enter:'Enter the Central Rotunda',gallery:'Enter the Digital Gallery',interactive:'Enter the interaction study',creator:'Read the Creator Card: IseFDK',exit:'Return to the Entrance'},ru:{enter:'Войти в Центральную ротонду',gallery:'Войти в цифровую галерею',interactive:'Войти в интерактивный этюд',creator:'Карточка автора IseFDK',exit:'Вернуться ко входу'}};
 function update(){const state=getState();for(const scene of scenes){const spec=manifest.scenes[scene.dataset.foundationScene][mobile.matches?'mobile':'desktop'],img=scene.querySelector('img'),file=state.quality==='light'&&spec.lightImage?spec.lightImage:spec.image;const src='architecture/'+file;if(img.getAttribute('src')!==src)img.src=src;const rect=fitImage(scene.clientWidth,scene.clientHeight,spec.width,spec.height,mobile.matches);for(const hit of scene.querySelectorAll('[data-foundation-target]')){const key=hit.dataset.foundationTarget,target=spec.targets[key==='enter'?'door':key]||spec.targets[key];hit.setAttribute('aria-label',labels[state.language][key]);if(!target){hit.hidden=true;continue;}hit.hidden=false;const box=targetBounds(target.polygon);const projected={left:rect.left+box.left*rect.width,top:rect.top+box.top*rect.height,width:box.width*rect.width,height:box.height*rect.height},area=mobile.matches?touchBounds(projected):projected;Object.assign(hit.style,{left:area.left+'px',top:area.top+'px',width:area.width+'px',height:area.height+'px',clipPath:mobile.matches?'none':'polygon('+target.polygon.map(([x,y])=>`${(x-box.left)/box.width*100}% ${(y-box.top)/box.height*100}%`).join(',')+')'});}}}
 for(const scene of scenes)new ResizeObserver(update).observe(scene);mobile.addEventListener('change',update);update();return{update};
}
