import fs from'node:fs';import path from'node:path';import assert from'node:assert/strict';import{fileURLToPath}from'node:url';import{rooms,exhibits}from'../src/data.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),out=path.join(root,'docs/museum'),html=fs.readFileSync(path.join(out,'index.html'),'utf8'),css=fs.readFileSync(path.join(out,'assets/style.css'),'utf8');
assert.equal((html.match(/data-room class=/g)||[]).length,rooms.length+exhibits.length);assert.equal((html.match(/<h1[ >]/g)||[]).length,1);assert.ok(html.includes('lang="ru"'));assert.ok(html.includes('id="main"'));assert.ok(html.includes('id="museum-plan"'));assert.ok(html.includes('data-room-title tabindex="-1"'));assert.ok(!/<iframe|<form/.test(html));assert.ok(!html.includes('schoditsya'));assert.ok(!html.includes('mailto:'));assert.ok(!html.includes('steam'));assert.ok(css.includes('prefers-reduced-motion'));assert.ok(css.includes('focus-visible'));
const ids=[...html.matchAll(/\bid="([^\"]+)"/g)].map(m=>m[1]);assert.equal(new Set(ids).size,ids.length,'unique IDs');
for(const m of html.matchAll(/href="#([^\"]+)"/g))assert.ok(ids.includes(m[1]),'anchor '+m[1]);
for(const m of html.matchAll(/(?:src|href|srcset)="([^\"]+)"/g)){let value=m[1].split(/[?#]/)[0];if(!value||/^(https?:|data:)/.test(value))continue;const file=path.resolve(out,value);assert.ok(file.startsWith(path.join(root,'docs')),'scoped reference '+value);assert.ok(fs.existsSync(file),'local reference '+value);}
for(const m of css.matchAll(/url\(['"]?([^'"\)]+)['"]?\)/g))assert.ok(fs.existsSync(path.resolve(out,'assets',m[1])),'font '+m[1]);
for(const p of exhibits){assert.ok(html.includes('id="exhibit-'+p.id+'"'));assert.ok(html.includes('https://github.com/IseFDK/'+p.repo));if(p.live)assert.ok(html.includes(p.live));}
const ledger=html.split('id="exhibit-ledger"')[1].split('<section class="plain-plan"')[0];assert.ok(ledger.includes('Без публичного демо'));assert.ok(!ledger.includes('Открыть проект'));assert.ok(html.includes('Пока здесь нет опубликованных игр'));assert.ok(html.includes('Неофициальный фан-проект'));
for(const file of ['assets/app.mjs','assets/sculpture.mjs','assets/geometry.mjs','assets/routes.mjs']){const source=fs.readFileSync(path.join(out,file),'utf8');for(const m of source.matchAll(/(?:from|import\()\s*['"](\.\/[^'"]+)/g))assert.ok(fs.existsSync(path.resolve(path.dirname(path.join(out,file)),m[1])),'module '+m[1]);}
const list=[];function walk(dir){for(const file of fs.readdirSync(dir)){const p=path.join(dir,file);fs.statSync(p).isDirectory()?walk(p):list.push(p);}}walk(out);const bytes=list.reduce((s,p)=>s+fs.statSync(p).size,0);assert.ok(bytes<1_800_000,'total museum payload budget');assert.ok(fs.statSync(path.join(out,'assets/app.mjs')).size<12000,'lazy runtime budget');console.log('Museum audit passed: 11 accessible room/exhibit views; local links, IDs, modules, truthful limits and payload budget ('+bytes+' bytes)');
