import test from 'node:test';
import assert from 'node:assert/strict';
import {projects,categories,filterProjects,readWorkState,workSearch,getProject} from '../src/projects.mjs';
test('only the six authorized projects, unique IDs and exact public sources',()=>{assert.deepEqual(projects.map(p=>p.id),['abyss','riso','aura','nocturne','ledger','last-signal']);assert.equal(new Set(projects.map(p=>p.id)).size,6);for(const p of projects){assert.ok(p.repo);assert.equal(p.decisions.length,3);assert.equal(p.steps.length,3);assert.ok(p.boundaries.length>90);assert.ok(p.note);assert.ok(p.categories.every(c=>categories.some(x=>x[0]===c)));}assert.equal(getProject('ledger').live,null);assert.equal(getProject('nocturne').repo,'nocturne-observatory');});
test('filtering works with category intersection, Russian and English text',()=>{assert.equal(filterProjects('ГРЕНИНДЗЯ').length,0);assert.deepEqual(filterProjects('RISO').map(p=>p.id),['riso']);assert.deepEqual(filterProjects('атлас').map(p=>p.id),['abyss','aura']);assert.deepEqual(filterProjects('', 'fullstack').map(p=>p.id),['ledger']);assert.equal(filterProjects('RISO','3d').length,0);assert.equal(filterProjects('Node.js','fullstack')[0].id,'ledger');});
test('empty, zero-result and whitespace requests',()=>{assert.equal(filterProjects('').length,6);assert.equal(filterProjects('   ').length,6);assert.equal(filterProjects('this does not exist').length,0);});
test('URL state round-trips and unknown category safely defaults',()=>{const state={query:'Полевой атлас',category:'tools'};assert.deepEqual(readWorkState(workSearch(state)),state);assert.deepEqual(readWorkState('?type=unknown&q=RISO'),{query:'RISO',category:'all'});assert.equal(workSearch({query:'',category:'all'}),'');assert.equal(readWorkState('?q='+'x'.repeat(150)).query.length,100);});
test('query strings remain text and never become generated HTML',()=>{const input='<script>alert(1)</script>';assert.deepEqual(readWorkState(workSearch({query:input,category:'all'})),{query:input,category:'all'});assert.equal(filterProjects(input).length,0);});
test('Last Signal is discoverable in both languages and only its actual category',()=>{for(const q of ['LAST SIGNAL','Последний сигнал','ночной поезд'])assert.deepEqual(filterProjects(q).map(p=>p.id),['last-signal']);assert.deepEqual(filterProjects('сигнал','editorial').map(p=>p.id),['last-signal']);assert.equal(filterProjects('сигнал','3d').length,0);assert.equal(filterProjects('сигнал','tools').length,0);const p=getProject('last-signal');assert.equal(p.live,'https://isefdk.github.io/last-signal/');assert.equal(p.repo,'last-signal');assert.equal(p.gallery.length,3);assert.equal(p.portrait.height,1708);assert.ok(p.imageAlt.length>30);assert.ok(p.gallery.every(g=>g.alt.length>30&&g.text.length>40));});
