import{prototypeCollection,corridorFrames,interactiveObjects,wings,copy}from'./spatial-data.mjs';import{parseMuseumHash,routeHash,clamp,cameraPose,worldTransform,nearestItem,magneticTarget}from'./engine.mjs';import{mountFolio}from'./folio.mjs';import{createProjectedScene}from'./projection.mjs';
const $=s=>document.querySelector(s),all=s=>[...document.querySelectorAll(s)];const mq=matchMedia('(prefers-reduced-motion:reduce)'),dossier=$('#museum-dossier');let state={...parseMuseumHash(location.hash),position:0,language:'en',quality:'full',motion:'system'},selectedItem=null,opener=null,sculpture=null,sculptureLoading=false,raf=0,lastScroll=0,lastTime=0,speed=0,settleTimer=0,interactionEpoch=0,travelMemory={gallery:0,interactive:0};
try{const prefs=JSON.parse(localStorage.getItem('museum-visitor-preferences')||'{}');for(const[k,values]of Object.entries({language:['en','ru'],quality:['full','light'],motion:['system','reduce','normal']}))if(values.includes(prefs[k]))state[k]=prefs[k];}catch{}
const sceneRenderers={gallery:createProjectedScene($('[data-scene=gallery]'),corridorFrames),interactive:createProjectedScene($('[data-scene=interactive]'),interactiveObjects)};
const reduced=()=>state.motion==='reduce'||(state.motion==='system'&&mq.matches);const itemsFor=wing=>wings[wing]?.items||[];
function project(id){return prototypeCollection.find(p=>p.id===id);}
function getSelectedItem(id,panel){return itemsFor(state.wing).find(p=>p.id===panel)||itemsFor(state.wing).find(p=>p.project===id&&p.id==='signal-observatory')||itemsFor(state.wing).find(p=>p.project===id)||null;}
function labels(){const c=copy[state.language];document.documentElement.lang=state.language;all('[data-copy]').forEach(e=>{e.textContent=c[e.dataset.copy]||e.textContent;});all('[data-frame-title]').forEach(e=>{const f=corridorFrames.find(f=>f.id===e.dataset.frameTitle);if(f)e.textContent=state.language==='ru'?f.titleRu:f.titleEn;});for(const p of prototypeCollection){const suffix=state.language==='ru'?'Ru':'En';for(const[field,property]of [['title','title'],['description','description'],['role','role'],['status','status'],['limits','limits']]){const e=$(`[data-project-${field}="${p.id}"]`);if(e)e.textContent=p[property+suffix]||p[property]||p.title;}}all('[data-motion-note]').forEach(e=>e.textContent=reduced()?c.reduced:'↑ / ↓ · Page Up / Down · Home / End');all('.scene').forEach(e=>e.setAttribute('aria-label',c.move));$('[data-close-dossier]').setAttribute('aria-label',c.close);const back=state.wing==='rotunda'?'exit':'back';$('#local-exit [data-copy]').textContent=c[back];document.title=(state.selected?project(state.selected)?.title:c[state.wing]||c.museum)+' — IseFDK Museum';folio?.update();}
function settings(){document.documentElement.classList.toggle('motion-reduce',reduced());document.documentElement.classList.toggle('quality-light',state.quality==='light');document.documentElement.dataset.motion=reduced()?'reduce':'normal';document.documentElement.dataset.quality=state.quality;sculpture?.setReduced(reduced());labels();renderCamera();}
const folio=mountFolio({getState:()=>state,onNavigate:({wing,selected})=>navigate({wing,selected,position:selected?getDefaultPosition(wing,selected):travelMemory[wing]||0}),onPreferences:prefs=>{Object.assign(state,prefs);try{localStorage.setItem('museum-visitor-preferences',JSON.stringify({language:state.language,quality:state.quality,motion:state.motion}));}catch{}settings();}});
function getDefaultPosition(wing,id){const item=itemsFor(wing).find(p=>p.project===id&&p.id==='signal-observatory')||itemsFor(wing).find(p=>p.project===id);return item?Math.max(0,item.depth-480):0;}
function scrollRange(){const e=$('#'+state.wing);return wings[state.wing]?Math.max(1,e.offsetHeight-innerHeight):0;}
function persistPosition(){if(wings[state.wing]&&!state.selected){state.position=clamp(scrollY/scrollRange(),0,1)*wings[state.wing].length;travelMemory[state.wing]=state.position;}history.replaceState({...state,panel:selectedItem?.id||null,inspectionOrigin:history.state?.inspectionOrigin||false},'',location.hash||'#entrance');}
function navigate(next,{replace=false,panel=null,inspectionOrigin=false}={}){persistPosition();const value={...state,...next,panel,inspectionOrigin};if(replace)history.replaceState(value,'',routeHash(value));else history.pushState(value,'',routeHash(value));applyRoute(value);}
function applyRoute(value,{initial=false,restore=false}={}){if($('#visitor-folio').open)$('#visitor-folio').close();if(dossier.open)dossier.close();document.documentElement.classList.remove('dossier-open');state={...state,...parseMuseumHash(location.hash),...value};if(!wings[state.wing])state.position=0;state.position=clamp(Number(state.position)||0,0,wings[state.wing]?.length||0);selectedItem=state.selected?getSelectedItem(state.selected,state.panel):null;document.body.dataset.currentRoom=state.wing;all('section[data-room]').forEach(e=>e.hidden=e.dataset.room!==state.wing);$('#local-exit').hidden=state.wing==='entrance';$('#local-exit').href=state.wing==='rotunda'?'#entrance':'#rotunda';document.documentElement.classList.toggle('dossier-open',Boolean(state.selected));all('[data-dossier]').forEach(e=>e.hidden=e.dataset.dossier!==state.selected);all('[data-project-title]').forEach(e=>e.id='dossier-title-'+e.dataset.projectTitle);const selected=project(state.selected);if(selected){const title=$(`[data-project-title="${selected.id}"]`);title.id='active-dossier-title';$('[data-dossier-index]').textContent=`${selected.label} / COLLECTION DOSSIER`;dossier.showModal();requestAnimationFrame(()=>$('[data-close-dossier]').focus({preventScroll:true}));}else{requestAnimationFrame(()=>{scrollTo({top:wings[state.wing]?state.position/wings[state.wing].length*scrollRange():0,behavior:'instant'});if(!initial){if(restore&&opener?.isConnected&&opener.closest('#'+state.wing))opener.focus({preventScroll:true});else $('#'+state.wing)?.querySelector('.scene')?.focus({preventScroll:true});}});}sculpture?.setActive(state.wing==='rotunda'&&state.quality==='full');if(state.wing==='rotunda'&&state.quality==='full')loadSculpture();settings();$('#museum-status').textContent=state.selected?`${copy[state.language].inspect}: ${selected?.title}`:copy[state.language][state.wing]||'';renderCamera();}
function renderCamera(){raf=0;const spec=wings[state.wing];if(!spec)return;const pose=cameraPose({position:state.position,selectedItem,reduced:reduced(),mobile:innerWidth<700,quality:state.quality});const world=$(`[data-world="${state.wing}"]`);world.style.transform=worldTransform(pose);sceneRenderers[state.wing].render(pose,{end:spec.end,quality:state.quality,language:state.language});world.dataset.cameraPosition=pose.position.toFixed(2);world.dataset.cameraYaw=String(pose.yaw);world.dataset.rawPosition=state.position.toFixed(2);$(`[data-progress="${state.wing}"]`).textContent=`${Math.round(state.position)} / ${spec.length}`;const near=nearestItem(spec.items,state.position+480),button=$(`[data-nearby="${state.wing}"]`);const visible=near&&!state.selected&&Math.abs(near.depth-state.position-480)<340;button.hidden=!visible;if(visible){button.textContent=`${copy[state.language].inspect} · ${project(near.project)?.title}`;button.dataset.item=near.id;}}
function onScroll(){if(!wings[state.wing]||state.selected)return;const now=performance.now(),next=clamp(scrollY/scrollRange(),0,1)*wings[state.wing].length;speed=(next-lastScroll)/Math.max(1,now-lastTime);lastScroll=next;lastTime=now;state.position=next;travelMemory[state.wing]=next;if(!raf)raf=requestAnimationFrame(renderCamera);clearTimeout(settleTimer);settleTimer=setTimeout(()=>{if(state.selected||$('#visitor-folio').open||reduced()||state.quality==='light')return;const target=magneticTarget(itemsFor(state.wing),state.position,0);if(target===null||Math.abs(target-state.position)<2)return;const start=state.position,begin=performance.now(),duration=240,epoch=interactionEpoch;function nudge(t){if(state.selected||$('#visitor-folio').open||epoch!==interactionEpoch||Math.abs(state.position-start)>100)return;const f=Math.min(1,(t-begin)/duration),p=start+(target-start)*(1-Math.pow(1-f,3));scrollTo({top:p/wings[state.wing].length*scrollRange(),behavior:'instant'});if(f<1)requestAnimationFrame(nudge);}requestAnimationFrame(nudge);},300);}
async function loadSculpture(){if(sculpture||sculptureLoading)return;sculptureLoading=true;try{const{mountSculpture}=await import('./sculpture.mjs');sculpture=mountSculpture($('#sculpture'),{reduced:reduced()});sculpture.setActive(state.wing==='rotunda'&&state.quality==='full');}catch{}}
function inspect(item,button){opener=button;persistPosition();const original=state.position;navigate({wing:state.wing,selected:item.project,position:original},{panel:item.id,inspectionOrigin:true});}
function closeInspection(){if(!state.selected)return;if(history.state?.inspectionOrigin){history.back();}else navigate({wing:state.wing,selected:null,position:state.position},{replace:true});}
document.addEventListener('click',e=>{const itemButton=e.target.closest('[data-item],[data-nearby]');if(itemButton&&!e.metaKey&&!e.ctrlKey){e.preventDefault();const id=itemButton.dataset.item,item=itemsFor(state.wing).find(p=>p.id===id);if(item)inspect(item,itemButton);return;}const link=e.target.closest('a[href^="#"]');if(!link||link.hash==='#main'||e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;e.preventDefault();const route=parseMuseumHash(link.hash);navigate({...route,position:route.selected?getDefaultPosition(route.wing,route.selected):travelMemory[route.wing]||0});});
$('[data-close-dossier]').onclick=closeInspection;dossier.addEventListener('cancel',e=>{e.preventDefault();closeInspection();});
all('[data-light]').forEach(button=>button.onclick=()=>{const evening=button.dataset.light==='evening';all('[data-light]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));all('.diorama-orb').forEach(e=>{e.style.background=evening?'radial-gradient(circle at 30% 25%,#fff4d7,#d5a975 42%,#7d6654 85%)':'';});});
function cancelSettling(){interactionEpoch++;clearTimeout(settleTimer);}
window.addEventListener('wheel',cancelSettling,{passive:true});window.addEventListener('touchmove',cancelSettling,{passive:true});window.addEventListener('keydown',cancelSettling);window.addEventListener('scroll',onScroll,{passive:true});window.addEventListener('resize',()=>{renderCamera();});window.addEventListener('popstate',()=>applyRoute(history.state||parseMuseumHash(location.hash),{restore:true}));window.addEventListener('hashchange',()=>{const route=parseMuseumHash(location.hash);if(route.wing!==state.wing||route.selected!==state.selected)applyRoute({...route,position:route.selected?getDefaultPosition(route.wing,route.selected):travelMemory[route.wing]||0});});mq.addEventListener('change',settings);
window.addEventListener('keydown',e=>{if(dossier.open||$('#visitor-folio').open||e.target.matches('input,select,textarea,button,a'))return;if(!wings[state.wing])return;let delta=0;if(e.key==='ArrowDown')delta=130;if(e.key==='ArrowUp')delta=-130;if(e.key==='PageDown')delta=innerHeight*.7;if(e.key==='PageUp')delta=-innerHeight*.7;if(e.key==='Home'){e.preventDefault();scrollTo({top:0,behavior:'instant'});}else if(e.key==='End'){e.preventDefault();scrollTo({top:scrollRange(),behavior:'instant'});}else if(delta){e.preventDefault();scrollBy({top:delta,behavior:'instant'});}});
window.addEventListener('museum-qa',e=>{if(e.detail?.motion)state.motion=e.detail.motion;settings();});
history.scrollRestoration='manual';const route=parseMuseumHash(location.hash);state={...state,...route,position:route.selected?getDefaultPosition(route.wing,route.selected):0};history.replaceState({...state},'',location.hash||'#entrance');document.documentElement.classList.add('enhanced');applyRoute(state,{initial:true});
